---

- hosts: all
  become: true
  tasks:

  - name: Install apache and php for ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd and php for CentOS
    dnf:
      name:
      - httpd
      - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"

