---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install apache and php package for Ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  # Centos
  - name: update respository index
    dnf:
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: Install httpd and php on CentOS
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == 'CentOS'
