---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    apt:
      update_cache: yes
    when: ansible_distribution == 'Ubuntu'

  - name: Install Apache2 on Ubuntu
    apt:
      name: apache2
      state: latest
    when: ansible_distribution == 'Ubuntu'

  - name: Install php support for Apache2
    apt:
      name: libapache2-mod-php
      state: latest
    when: ansible_distribution == 'Ubuntu'

  # Centos
  - name: update respository index
    dnf:
      update_cache: yes
    when: ansible_distribution == 'CentOS'

  - name: Install httpd on CentOS
    dnf:
      name: httpd
      state: latest
    when: ansible_distribution == 'CentOS'

  - name: Install php support for apache for Centos
    dnf:
      name: php
      state: latest
    when: ansible_distribution == 'CentOS'
