---

- hosts: all
  become: true
  tasks:

  - name: update respository index
    apt:
      update_cache: yes

  - name: Remove Apache2 on Ubuntu
    apt:
      name: apache2
      state: absent

  - name: Remove php support for Apache2
    apt:
      name: libapache2-mod-php
      state: absent
