---

- hosts: all
  become: true
  pre_tasks:

  - name: update repo cache (CentOS)
    tags: always
    dnf:
      update_cache: yes
    changed_when: false  # if cache is updated do not register as a change
    when: ansible_distribution == "CentOS"

  - name: update repo cache (Ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false  # if cache is updated do not register as a change
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  tasks:

  - name: add ssh key for simone
    tags: always
    authorized_key:
      user: simone
      key: "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHVWHbxzI2xJCQh3w5E5qic1c0LYBaSpz85FbT/RExDk ansible_default"


- hosts: web_servers
  become: true

  tasks:
  - name: Install apache and php for ubuntu
    tags: apache,apache2,ubuntu
    apt:
      name:
      - apache2
      - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: Install httpd and php for CentOS
    tags: httpd,Centos
    dnf:
      name:
      - httpd
      - php
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start httpd (CentOS)
    tags: apache, centos, httpd
    service:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: copy default html file for site
    tags: apache,apache2
    copy:
      src: default_site.html  # detination of files folder is assumed
      dest: /var/www/html/index.html
      owner: root
      group: root
      mode: 0644

  - name: change a line in a file and restart the service
    tags: apache,apache2
    lineinfile:
      path: /var/www/html/index.html
      search_string: '<p>Ansible is'
      line: <p>Ansible continues to change lines</p>
    when: ansible_distribution == "Ubuntu"
    register: apache2_change_line

  - name: restart apache (Ubuntu)
    tags: apache,apache2,ubuntu
    service:
      name: apache2
      state: restarted
    when: apache2_change_line.changed

- hosts: file_servers
  become: true

  tasks:
  - name: install samba package
    tags: samba
    package:
      name: samba
      state: latest

- hosts: workstations
  become: true

  tasks:
  - name: install unzip
    tags: unzip
    package:
      name: unzip
      state: latest

  - name: install terraform
    tags: terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/1.8.0/terraform_1.8.0_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root
