- name: Install apache and php
  tags: apache,https,php
  package:
    name:
    - "{{ apache_package_name }}"
    - "{{ php_package_name }}"
    - "{{ ansible_package_name }}"
    state: latest

- name: start and enable apache services
  tags: apache,httpd
  service:
    name: "{{ apache_service }}"
    state: started
    enabled: yes

- name: change email address for admin
  tags: apache,ubuntu
  lineinfile:
    path: /etc/apache2/sites-available/000-default.conf
    search_string: 'ServerAdmin'
    line: ServerAdmin serveradmin@somewhere.net
  when: ansible_distribution == "Ubuntu"
  notify: restart_apache

- name: copy default html file for site
  tags: apache,apache2,httpd
  copy:
    src: default_site.html  # relative destination of files folder is assumed
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
